name: 'Checkout Merge'
description: 'Generate a merge commit'
author: 'jsoref'
branding:
  icon: 'git-commit'
  color: 'green'
inputs:
  base_ref:
    description: |
      This commit will be refetched (to give the merge the best chance of
      succeeding) and used as the base for the merge.
    default: ${{ github.event.pull_request.base.ref }}
    required: false
  head_ref:
    description: |
      This commit will be fetched and merged into the base commit.
    default: ${{ github.event.pull_request.head.sha }}
    required: false
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to the repository'
    default: "."
    required: false
  do_not_report:
    description: 'Suppress reporting errors (consumers would report the message themselves)'
    default: ''
    required: false
outputs:
  message:
    description: "User facing message about attempt to merge"
    value: ${{ steps.merge.outputs.message }}
  status:
    description: "Whether the merge succeeded"
    value: ${{ steps.merge.status }}
runs:
  using: composite
  steps:
    - id: merge
      shell: bash
      env:
        INPUT_BASE_REF: ${{ inputs.base_ref }}
        INPUT_HEAD_REF: ${{ inputs.head_ref }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_DO_NOT_REPORT: ${{ inputs.do_not_report }}
        GH_TOKEN: ${{ github.token }}
      run: ${{ github.action_path }}/merge
